name: Deploy Angular Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: sudo docker build -t amitkumar023/angular-app .
      - name: Publish Image to docker hub
        run: sudo docker push amitkumar023/angular-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull amitkumar023/angular-app:latest
      - name: Delete old container
        run: sudo docker rm -f angular-app-container
      - name: Run Docker Container
        run: sudo docker run -d -p 4200:80 --name angular-app-container amitkumar023/angular-app
